on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:
  gha-preview-change-plan:
    name: review change plan for gha-preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure shared pipeline job environment
        uses: ./.github/actions/shared-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-preview
      - name: terraform plan for gha-preview environment
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-preview
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          plan: true

  # github repository configuration has gha-preview environment defined
  # and requires team member approval to perform this job
  gha-preview-apply-changes:
    name: deploy gha-preview changes
    needs: [ validate-terraform, gha-preview-change-plan ]
    runs-on: ubuntu-latest
    environment:
      name: gha-preview
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure shared pipeline job environment
        uses: ./.github/actions/shared-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-preview
      - name: setup runner
        uses: ThoughtWorks-DPS/lab-runner-setup-action@main
        with:
          install-awspec: true
      - name: apply and test changes to gha-preview eks cluster
        uses: ThoughtWorks-DPS/terraform-action@main
        env:
          TF_WORKSPACE: gha-preview
        with:
          terraform-cloud-token: $TERRAFORM_CLOUD_TOKEN
          awspec-test: true
          test-assume-role: true
          apply: true
      - name: update cluster manager credentials
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
        run: bash scripts/write_cluster_credentials.sh gha-preview

  deploy-core-services:
    name: deploy core services
    needs: gha-preview-apply-changes
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure shared pipeline job environment
        uses: ./.github/actions/shared-pipeline-env
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-preview
      - name: deploy and test core cluster services
        uses: ./.github/actions/deploy-core-services
        with:
          secrethub-creds: ${{ secrets.SECRETHUB_CREDENTIAL }}
          tfvar-env: gha-preview
